version: 2

updates:
  - package-ecosystem: cargo
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Denver
    allow:
      - dependency-name: tantivy
        dependency-type: direct
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - tantivy
