/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RuntimeInfo {
  packageVersion: string
  tantivyVersion: string
  nativeAbiVersion: number
  storageBackends: Array<string>
}
export declare function runtimeInfo(): RuntimeInfo
